= Prepare your AWS account
:doctype: book

If you don't already have an AWS account, create one by following the https://aws.amazon.com/[step-by-step instructions]. Your AWS account is automatically signed up for all AWS services. You are charged only for the services you use.

== Amazon EC2 key pairs

You need at least one EC2 key pair in the AWS account in the Region where you plan to deploy the Quick Start. To create a key pair, see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[Amazon EC2 key pairs and Linux instances].

Take note of the key-pair name as it is needed during the deployment.

NOTE:  For testing or evaluation purposes, we recommend creating a new key pair instead of using an existing one.

== Valid domain name

This Quick Start requires you to have established ownership of the parent domain under which the web application will be served. If you want to register a domain, see https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-register-update.html[Registering a public domain].

If you have registered the domain using AWS Route 53, then the hosted zone is preconfigured, and no additional configuration is necessary.

Otherwise, you should set up a hosted zone in your AWS account, with the required name server, start of authority, CNAME, and text records. For further details on how to create a public hosted zone, see https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/AboutHZWorkingWith.html[Working with public hosted zones].